Repository appleboy/gorush, pull requests merged in 2020-02, with the labels that each got.

#461 feat(server): support graceful shutdown
  gorush/server_lambda.go
  gorush/server_normal.go
  gorush/server_test.go
  main.go
Labels: Feature

#463 chore(rpc): graceful shutdown for RPC server
  main.go
  rpc/server.go
Labels: Feature

#464 chore(log): ignore /healthz request log
  docker-compose.yml
  go.mod
  go.sum
  gorush/log.go
  gorush/server.go
Labels: enhancement

#437 Allow ability to explicitly set APNS priority
  gorush/notification_apns.go
Labels: enhancement

#478 Fix Redis stats storage concurrency issues
  storage/redis/redis.go
  storage/redis/redis_test.go
Labels: bug
