Repository appleboy/gorush, pull requests merged in 2020-05, with the labels that each got.

#506 chore: upgrade gin to 1.6.3 performance
  go.mod
  go.sum
Labels: enhancement

#509 ReImplement DialTLS fix from apns2
  gorush/notification_apns.go
Labels: bug, enhancement

#516 fix config path in readme #514
  .gitignore
  README.md
  contrib/init/debian/README.md
Labels: document
