Repository appleboy/gorush, pull requests merged in 2021-07, with the labels that each got.

#579 refactor: remove duplicated of init code.
  go.mod
  go.sum
  gorush/main_test.go
  gorush/notification_fcm_test.go
  gorush/notification_hms_test.go
  gorush/server_normal.go
  gorush/server_test.go
Labels: enhancement

#589 chore: support single queue and multiple worker
  config/config.go
  config/config_test.go
  gorush/const.go
  gorush/feedback_test.go
  gorush/global.go
  gorush/main_test.go
  gorush/notification.go
  gorush/notification_apns.go
  gorush/notification_apns_test.go
  gorush/notification_fcm.go
  gorush/notification_fcm_test.go
  gorush/notification_hms.go
  gorush/notification_hms_test.go
  gorush/notification_test.go
  gorush/worker.go
  gorush/worker_test.go
  logx/log_test.go
  main.go
  queue/queue.go
  queue/simple/simple.go
  queue/thread.go
  queue/worker.go
  router/server.go
  router/server_lambda.go
  router/server_normal.go
  router/server_test.go
  rpc/server.go
  rpc/server_test.go
  status/status_test.go
  storage/badger/badger_test.go
  storage/boltdb/boltdb_test.go
  storage/buntdb/buntdb_test.go
  storage/leveldb/leveldb_test.go
  storage/redis/redis_test.go
Labels: enhancement

#591 Only initial MaxConcurrentIOSPushes once.
  gorush/notification.go
  gorush/notification_apns.go
  gorush/notification_apns_test.go
  gorush/notification_fcm.go
  gorush/notification_fcm_test.go
  gorush/notification_hms.go
  main.go
  queue/queue.go
  queue/simple/simple.go
  queue/worker.go
  router/server.go
  router/server_test.go
  rpc/server.go
Labels: bug

#558 A basic Helm chart
  helm/gorush/.helmignore
  helm/gorush/Chart.yaml
  helm/gorush/templates/NOTES.txt
  helm/gorush/templates/_helpers.tpl
  helm/gorush/templates/configmap.yml
  helm/gorush/templates/deployment.yaml
  helm/gorush/templates/hpa.yaml
  helm/gorush/templates/ingress.yaml
  helm/gorush/templates/service.yaml
  helm/gorush/templates/serviceaccount.yaml
  helm/gorush/values.yaml
Labels: enhancement

#600 chore(queue): support NSQ as backend.
  README.md
  config/config.go
  config/config_test.go
  config/testdata/config.yml
  core/queue.go
  go.mod
  go.sum
  gorush/notification_apns.go
  gorush/notification_fcm.go
  gorush/notification_hms.go
  main.go
  queue/nsq/nsq.go
  queue/queue.go
  queue/simple/simple.go
  queue/simple/simple_test.go
  queue/worker.go
  router/server.go
  status/status.go
Labels: Feature

#606 chore: init log package
  gorush/main_test.go
  logx/log.go
  queue/nsq/README.md
  queue/nsq/nsq_test.go
  queue/simple/simple_test.go
  router/server_test.go
  rpc/server_test.go
  status/status_test.go
Labels: enhancement
